version: "3.8"
x-logging: &default-logging
  options:
    max-size: "10m"
    max-file: "2"
  driver: json-file

services:
  redis:
    image: redis:6-alpine
    container_name: redis_${PROJECT_PREFIX:?not set}
    volumes:
      - ./redis.conf:/usr/local/etc/redis
    networks:
      - traefik-net
    restart: always
    logging: *default-logging

networks:
  traefik-net:
    name: traefik-net
    external: true
