name: Setup
description: Setup
author: "danicc097@gmail.com"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: "^1.22.0"

    # - name: Setup Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: "3.9"

    - uses: actions/setup-node@v3
      with:
        node-version: "20.9.0"

    - uses: pnpm/action-setup@v2
      with:
        version: 8.3.1
        run_install: false

    - name: Setup pnpm cache (1)
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Setup pnpm cache (2)
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Update
      shell: bash
      run: |
        sudo apt-get update

    - name: Install dependencies
      shell: bash
      run: |
        source .envrc

        echo Bootstrapping...

        { yes y 2>/dev/null || :; } | project bootstrap

        # project e2e.sync-deps # won't use python playwright

        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "$HOME/bin" >> $GITHUB_PATH
