name: Setup
description: Setup
author: "danicc097@gmail.com"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: "^1.18.4"

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: "corretto"
        java-version: "17"

    - name: Install dependencies
      shell: bash
      run: |
        source .envrc

        project install-tools
        project fetch.openapi-generator
        project fetch.swagger-ui
        bin/scripts/install-pg_format.sh
        bin/scripts/install-mkcert.sh

        mv .env.ci .env
