name: Setup
description: Setup
author: "danicc097@gmail.com"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: "^1.19.1"

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      shell: bash
      run: |
        source .envrc

        project e2e.sync-deps --x-env=ci
        project install-tools --x-env=ci
        project fetch.swagger-ui --x-env=ci
        bin/scripts/install-pg_format.sh
        bin/scripts/install-mkcert.sh
        bin/scripts/install-proto.sh

        git clone https://github.com/danicc097/traefik-boostrap.git
        docker network create traefik-net || true
        cd traefik-boostrap
        ./mkcert-certificates
        ./compose-up

        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "$HOME/bin" >> $GITHUB_PATH
