# https://github.com/MarioCarrion/todo-api-microservice-example/blob/main/.golangci.yml

linters:
  enable-all: true
  disable:
    - ireturn # oapi-codegen strict handlers
    # - interfacebloat
    - thelper
    - testpackage
    - depguard
    # - json(camel)
    - funlen
    - lll
    - wsl
    - nosnakecase
    - godox # marks TODO, FIX, ...
    - forbidigo # fmt banned, etc.
    - goerr113
    - gofumpt
    - gomnd
    - nonamedreturns
    # deprecated
    - exhaustivestruct
    - golint
    - interfacer
    - maligned
    - scopelint
    # disabled because of go1.18, added to avoid the initial warning when running
    # https://github.com/golangci/golangci-lint/issues/2649
    - bodyclose
    - contextcheck
    - nilerr
    - noctx
    # - rowserrcheck
    - sqlclosecheck
    - structcheck
    - unparam
    - wastedassign

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - io/ioutil.ReadFile
      - io.Copy(*bytes.Buffer)
      - io.Copy(os.Stdout)
  gofmt:
    simplify: true
  lll:
    line-length: 130
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: goCamel
        yaml: goCamel
  staticcheck:
    go: "1.21"
    checks:
      - "all"
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/danicc097/openapi-go-gin-postgres-sqlc)
    skip-generated: true
  exhaustruct:
    include:
      - "github.com/danicc097/openapi-go-gin-postgres-sqlc/internal.*Params"
  ireturn:
    allow:
      - error
      - stdlib
      - "go.opentelemetry.io/otel/trace.Span"
  varnamelen:
    max-distance: 20
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-names:
      - id
      - tx
      - ctx
    ignore-decls:
      - d db.DBTX
      - c *gin.Context
      - b bytes.Buffer
      - h http.Handler
      - id string
      - ok bool
      - r *http.Request
      - w http.ResponseWriter
  wrapcheck:
    ignoreSigs:
      - internaldomain.WrapErrorf(
      - internaldomain.NewErrorf(
      - internal.NewErrorf(
      - internal.WrapErrorf(
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
    ignorePackageGlobs:
      - github.com/danicc097/openapi-go-gin-postgres-sqlc/*
issues:
  exclude-rules:
    - path: "internal/testutil/*" # doesn't work with internal/... for some reason
      linters:
        - gosec
    - path: "."
      linters:
        - gci
        - nolintlint
    - path: internal/gen/
      linters:
        - lll
        - godot
        - wsl
    # All tests
    - path: _test\.go
      linters:
        - errcheck
        - cyclop
        - errchkjson
        - exhaustruct
        - funlen
        - goerr113
        - lll
        - nonamedreturns
        - nosnakecase
        - varnamelen
        - wrapcheck
    # Handles the C4 diagrams
    - path: internal/doc/doc.go
      linters:
        - lll
        - revive
        - stylecheck
    # Final binaries
    - path: cmd/
      linters:
        - cyclop
        - funlen
        - gocognit
        - unparam
    - path: cmd/internal/repos/postgresql.go
      linters:
        - revive # blank-imports
    - path: internal/memcached/task.go
      linters:
        - lll
    # Because of the env var testing and using t.Setenv
    - path: internal/envvar/envvar_test.go
      linters:
        - paralleltest
        - thelper
        - tparallel
    # Because these are tools
    - path: internal/tools/tools.go
      linters:
        - typecheck
