version: "3.8"
x-logging: &default-logging
  options:
    max-size: "10m"
    max-file: "2"
  driver: json-file

# Debug config with docker-compose --env-file <...> config
services:
  db:
    image: postgres:13-alpine
    container_name: postgres_db_${PROJECT_PREFIX:?not set}_${APP_ENV:?not set}
    user: postgres
    shm_size: 2g
    networks:
      - traefik-net
    environment:
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./db/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./db/.psqlrc:/var/lib/postgresql/.psqlrc
    command: postgres -c "config_file=/etc/postgresql/postgresql.conf"
    ports:
      - ${DB_PORT:?not set}:5432
    env_file:
      - .env.${APP_ENV:?not set}
    restart: unless-stopped
    logging: *default-logging

networks:
  traefik-net:
    name: traefik-net
    external: true
