FROM golang:1.19-alpine AS build

WORKDIR /go/src
COPY go.* ./
# RUN go mod download # it will access network/cache, which is not necessary with -mod=vendor
COPY ./cmd/oidc-server/. .
ENV CGO_ENABLED=0
RUN --mount=type=cache,target=/root/.cache/go-build \
  GOWORK=off go build -mod=vendor -o oidc-server ./cmd/oidc-server

FROM alpine:3.15 AS runtime

RUN apk --no-cache add ca-certificates

ENV GIN_MODE=release
COPY --from=build /go/src/oidc-server ./
