// Code generated by project. DO NOT EDIT.

package repos

type Repos struct {
	Activity        Activity
	DemoTwoWorkItem DemoTwoWorkItem
	DemoWorkItem    DemoWorkItem
	KanbanStep      KanbanStep
	Notification    Notification
	Project         Project
	Team            Team
	TimeEntry       TimeEntry
	User            User
	WorkItem        WorkItem
	WorkItemComment WorkItemComment
	WorkItemTag     WorkItemTag
	WorkItemType    WorkItemType
}

func New(activity Activity, demoTwoWorkItem DemoTwoWorkItem, demoWorkItem DemoWorkItem, kanbanStep KanbanStep, notification Notification, project Project, team Team, timeEntry TimeEntry, user User, workItem WorkItem, workItemComment WorkItemComment, workItemTag WorkItemTag, workItemType WorkItemType) *Repos {
	return &Repos{
		Activity: activity, DemoTwoWorkItem: demoTwoWorkItem, DemoWorkItem: demoWorkItem, KanbanStep: kanbanStep, Notification: notification, Project: project, Team: team, TimeEntry: timeEntry, User: user, WorkItem: workItem, WorkItemComment: workItemComment, WorkItemTag: workItemTag, WorkItemType: workItemType,
	}
}
