// Code generated by counterfeiter. DO NOT EDIT.
package repostesting

import (
	"context"
	"sync"

	"github.com/danicc097/openapi-go-gin-postgres-sqlc/internal/repos"
	"github.com/danicc097/openapi-go-gin-postgres-sqlc/internal/repos/postgresql/gen/db"
)

type FakeTeam struct {
	CreateStub        func(context.Context, db.DBTX, repos.TeamCreateParams) (*db.Team, error)
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 context.Context
		arg2 db.DBTX
		arg3 repos.TeamCreateParams
	}
	createReturns struct {
		result1 *db.Team
		result2 error
	}
	createReturnsOnCall map[int]struct {
		result1 *db.Team
		result2 error
	}
	DeleteStub        func(context.Context, db.DBTX, int) (*db.Team, error)
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		arg1 context.Context
		arg2 db.DBTX
		arg3 int
	}
	deleteReturns struct {
		result1 *db.Team
		result2 error
	}
	deleteReturnsOnCall map[int]struct {
		result1 *db.Team
		result2 error
	}
	TeamByIDStub        func(context.Context, db.DBTX, int) (*db.Team, error)
	teamByIDMutex       sync.RWMutex
	teamByIDArgsForCall []struct {
		arg1 context.Context
		arg2 db.DBTX
		arg3 int
	}
	teamByIDReturns struct {
		result1 *db.Team
		result2 error
	}
	teamByIDReturnsOnCall map[int]struct {
		result1 *db.Team
		result2 error
	}
	TeamByNameStub        func(context.Context, db.DBTX, string, int) (*db.Team, error)
	teamByNameMutex       sync.RWMutex
	teamByNameArgsForCall []struct {
		arg1 context.Context
		arg2 db.DBTX
		arg3 string
		arg4 int
	}
	teamByNameReturns struct {
		result1 *db.Team
		result2 error
	}
	teamByNameReturnsOnCall map[int]struct {
		result1 *db.Team
		result2 error
	}
	UpdateStub        func(context.Context, db.DBTX, int, repos.TeamUpdateParams) (*db.Team, error)
	updateMutex       sync.RWMutex
	updateArgsForCall []struct {
		arg1 context.Context
		arg2 db.DBTX
		arg3 int
		arg4 repos.TeamUpdateParams
	}
	updateReturns struct {
		result1 *db.Team
		result2 error
	}
	updateReturnsOnCall map[int]struct {
		result1 *db.Team
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTeam) Create(arg1 context.Context, arg2 db.DBTX, arg3 repos.TeamCreateParams) (*db.Team, error) {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 context.Context
		arg2 db.DBTX
		arg3 repos.TeamCreateParams
	}{arg1, arg2, arg3})
	stub := fake.CreateStub
	fakeReturns := fake.createReturns
	fake.recordInvocation("Create", []interface{}{arg1, arg2, arg3})
	fake.createMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTeam) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeTeam) CreateCalls(stub func(context.Context, db.DBTX, repos.TeamCreateParams) (*db.Team, error)) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = stub
}

func (fake *FakeTeam) CreateArgsForCall(i int) (context.Context, db.DBTX, repos.TeamCreateParams) {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	argsForCall := fake.createArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeTeam) CreateReturns(result1 *db.Team, result2 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 *db.Team
		result2 error
	}{result1, result2}
}

func (fake *FakeTeam) CreateReturnsOnCall(i int, result1 *db.Team, result2 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 *db.Team
			result2 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 *db.Team
		result2 error
	}{result1, result2}
}

func (fake *FakeTeam) Delete(arg1 context.Context, arg2 db.DBTX, arg3 int) (*db.Team, error) {
	fake.deleteMutex.Lock()
	ret, specificReturn := fake.deleteReturnsOnCall[len(fake.deleteArgsForCall)]
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		arg1 context.Context
		arg2 db.DBTX
		arg3 int
	}{arg1, arg2, arg3})
	stub := fake.DeleteStub
	fakeReturns := fake.deleteReturns
	fake.recordInvocation("Delete", []interface{}{arg1, arg2, arg3})
	fake.deleteMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTeam) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakeTeam) DeleteCalls(stub func(context.Context, db.DBTX, int) (*db.Team, error)) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = stub
}

func (fake *FakeTeam) DeleteArgsForCall(i int) (context.Context, db.DBTX, int) {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	argsForCall := fake.deleteArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeTeam) DeleteReturns(result1 *db.Team, result2 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 *db.Team
		result2 error
	}{result1, result2}
}

func (fake *FakeTeam) DeleteReturnsOnCall(i int, result1 *db.Team, result2 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	if fake.deleteReturnsOnCall == nil {
		fake.deleteReturnsOnCall = make(map[int]struct {
			result1 *db.Team
			result2 error
		})
	}
	fake.deleteReturnsOnCall[i] = struct {
		result1 *db.Team
		result2 error
	}{result1, result2}
}

func (fake *FakeTeam) TeamByID(arg1 context.Context, arg2 db.DBTX, arg3 int) (*db.Team, error) {
	fake.teamByIDMutex.Lock()
	ret, specificReturn := fake.teamByIDReturnsOnCall[len(fake.teamByIDArgsForCall)]
	fake.teamByIDArgsForCall = append(fake.teamByIDArgsForCall, struct {
		arg1 context.Context
		arg2 db.DBTX
		arg3 int
	}{arg1, arg2, arg3})
	stub := fake.TeamByIDStub
	fakeReturns := fake.teamByIDReturns
	fake.recordInvocation("TeamByID", []interface{}{arg1, arg2, arg3})
	fake.teamByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTeam) TeamByIDCallCount() int {
	fake.teamByIDMutex.RLock()
	defer fake.teamByIDMutex.RUnlock()
	return len(fake.teamByIDArgsForCall)
}

func (fake *FakeTeam) TeamByIDCalls(stub func(context.Context, db.DBTX, int) (*db.Team, error)) {
	fake.teamByIDMutex.Lock()
	defer fake.teamByIDMutex.Unlock()
	fake.TeamByIDStub = stub
}

func (fake *FakeTeam) TeamByIDArgsForCall(i int) (context.Context, db.DBTX, int) {
	fake.teamByIDMutex.RLock()
	defer fake.teamByIDMutex.RUnlock()
	argsForCall := fake.teamByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeTeam) TeamByIDReturns(result1 *db.Team, result2 error) {
	fake.teamByIDMutex.Lock()
	defer fake.teamByIDMutex.Unlock()
	fake.TeamByIDStub = nil
	fake.teamByIDReturns = struct {
		result1 *db.Team
		result2 error
	}{result1, result2}
}

func (fake *FakeTeam) TeamByIDReturnsOnCall(i int, result1 *db.Team, result2 error) {
	fake.teamByIDMutex.Lock()
	defer fake.teamByIDMutex.Unlock()
	fake.TeamByIDStub = nil
	if fake.teamByIDReturnsOnCall == nil {
		fake.teamByIDReturnsOnCall = make(map[int]struct {
			result1 *db.Team
			result2 error
		})
	}
	fake.teamByIDReturnsOnCall[i] = struct {
		result1 *db.Team
		result2 error
	}{result1, result2}
}

func (fake *FakeTeam) TeamByName(arg1 context.Context, arg2 db.DBTX, arg3 string, arg4 int) (*db.Team, error) {
	fake.teamByNameMutex.Lock()
	ret, specificReturn := fake.teamByNameReturnsOnCall[len(fake.teamByNameArgsForCall)]
	fake.teamByNameArgsForCall = append(fake.teamByNameArgsForCall, struct {
		arg1 context.Context
		arg2 db.DBTX
		arg3 string
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.TeamByNameStub
	fakeReturns := fake.teamByNameReturns
	fake.recordInvocation("TeamByName", []interface{}{arg1, arg2, arg3, arg4})
	fake.teamByNameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTeam) TeamByNameCallCount() int {
	fake.teamByNameMutex.RLock()
	defer fake.teamByNameMutex.RUnlock()
	return len(fake.teamByNameArgsForCall)
}

func (fake *FakeTeam) TeamByNameCalls(stub func(context.Context, db.DBTX, string, int) (*db.Team, error)) {
	fake.teamByNameMutex.Lock()
	defer fake.teamByNameMutex.Unlock()
	fake.TeamByNameStub = stub
}

func (fake *FakeTeam) TeamByNameArgsForCall(i int) (context.Context, db.DBTX, string, int) {
	fake.teamByNameMutex.RLock()
	defer fake.teamByNameMutex.RUnlock()
	argsForCall := fake.teamByNameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeTeam) TeamByNameReturns(result1 *db.Team, result2 error) {
	fake.teamByNameMutex.Lock()
	defer fake.teamByNameMutex.Unlock()
	fake.TeamByNameStub = nil
	fake.teamByNameReturns = struct {
		result1 *db.Team
		result2 error
	}{result1, result2}
}

func (fake *FakeTeam) TeamByNameReturnsOnCall(i int, result1 *db.Team, result2 error) {
	fake.teamByNameMutex.Lock()
	defer fake.teamByNameMutex.Unlock()
	fake.TeamByNameStub = nil
	if fake.teamByNameReturnsOnCall == nil {
		fake.teamByNameReturnsOnCall = make(map[int]struct {
			result1 *db.Team
			result2 error
		})
	}
	fake.teamByNameReturnsOnCall[i] = struct {
		result1 *db.Team
		result2 error
	}{result1, result2}
}

func (fake *FakeTeam) Update(arg1 context.Context, arg2 db.DBTX, arg3 int, arg4 repos.TeamUpdateParams) (*db.Team, error) {
	fake.updateMutex.Lock()
	ret, specificReturn := fake.updateReturnsOnCall[len(fake.updateArgsForCall)]
	fake.updateArgsForCall = append(fake.updateArgsForCall, struct {
		arg1 context.Context
		arg2 db.DBTX
		arg3 int
		arg4 repos.TeamUpdateParams
	}{arg1, arg2, arg3, arg4})
	stub := fake.UpdateStub
	fakeReturns := fake.updateReturns
	fake.recordInvocation("Update", []interface{}{arg1, arg2, arg3, arg4})
	fake.updateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTeam) UpdateCallCount() int {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	return len(fake.updateArgsForCall)
}

func (fake *FakeTeam) UpdateCalls(stub func(context.Context, db.DBTX, int, repos.TeamUpdateParams) (*db.Team, error)) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = stub
}

func (fake *FakeTeam) UpdateArgsForCall(i int) (context.Context, db.DBTX, int, repos.TeamUpdateParams) {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	argsForCall := fake.updateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeTeam) UpdateReturns(result1 *db.Team, result2 error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = nil
	fake.updateReturns = struct {
		result1 *db.Team
		result2 error
	}{result1, result2}
}

func (fake *FakeTeam) UpdateReturnsOnCall(i int, result1 *db.Team, result2 error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = nil
	if fake.updateReturnsOnCall == nil {
		fake.updateReturnsOnCall = make(map[int]struct {
			result1 *db.Team
			result2 error
		})
	}
	fake.updateReturnsOnCall[i] = struct {
		result1 *db.Team
		result2 error
	}{result1, result2}
}

func (fake *FakeTeam) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	fake.teamByIDMutex.RLock()
	defer fake.teamByIDMutex.RUnlock()
	fake.teamByNameMutex.RLock()
	defer fake.teamByNameMutex.RUnlock()
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTeam) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ repos.Team = new(FakeTeam)
