#!/bin/bash

exit_code=0

CWD="$(dirname -- "$0")"

echo
echo "Testing for file discrepancies..."

for got_file in "$CWD"/got/*; do
  snapshot_file="$CWD/snapshot/${got_file##*/got/}"
  if [[ ! -f "$snapshot_file" ]]; then
    echo "ERROR: snapshot $snapshot_file does not exist" >&2
    exit_code=1
    continue
  fi

  if ! diff -u --color=always "$snapshot_file" "$got_file" >&2; then
    exit_code=1
  fi
done

exit $exit_code
