#!/bin/bash

exit_code=0

CWD="$(dirname -- "$0")"

echo
echo "Testing for file discrepancies..."

for snapshot_file in "$CWD"/snapshot/*; do
  got_file="$CWD/got/${snapshot_file##*/snapshot/}"
  if [[ ! -f "$got_file" ]]; then
    echo "ERROR: $got_file does not exist" >&2
    exit_code=1
  fi

  if ! diff -u --color=always "$snapshot_file" "$got_file" >&2; then
    echo "ERROR: $snapshot_file and $got_file differ." >&2
    exit_code=1
  fi
done

exit $exit_code
