version: "3.8"
x-logging: &default-logging
  options:
    max-size: "10m"
    max-file: "2"
  driver: json-file

services:
  vault:
    image: vault:1.9.8
    container_name: vault_${PROJECT_PREFIX:?not set}
    # ports:
    #   - "8300:8300"
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
    networks:
      - traefik-net
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8300"
    logging: *default-logging

networks:
  traefik-net:
    name: traefik-net
    external: true
