import React, { useEffect, useState } from 'react'
import { BrowserRouter, Route, Routes } from 'react-router-dom'
import 'src/assets/css/fonts.css'
import 'src/assets/css/overrides.css'
import 'src/assets/css/pulsate.css'
import FallbackLoading from 'src/components/Loading/FallbackLoading'
import { Button, Card, Popover, Space, Text, Textarea } from '@mantine/core'
import DynamicForm, { type SelectOptions, type DynamicFormOptions, InputOptions } from 'src/utils/formGeneration'
import type { CreateWorkItemRequest, WorkItemRole } from 'src/gen/model'
import type { GetKeys, RecursiveKeyOfArray, PathType } from 'src/types/utils'
import { FormProvider, useForm, useFormState, useWatch } from 'react-hook-form'
import { ajvResolver } from '@hookform/resolvers/ajv'
import { fullFormats } from 'ajv-formats/dist/formats'
import { parseSchemaFields } from 'src/utils/jsonSchema'
import { colorSwatchComponentInputOption } from 'src/components/formGeneration/components'
import { CodeHighlight } from '@mantine/code-highlight'
import { useFormSlice } from 'src/slices/form'
import { entries } from 'src/utils/object'
import { JSONSchemaType } from 'ajv'
import { JSON_SCHEMA, OPERATION_AUTH } from 'src/config'
import { Tooltip as ReactTooltip } from 'react-tooltip'
import { AppTourProvider } from 'src/tours/AppTourProvider'
import { useTour } from '@reactour/tour'
import { IconCheck, IconCross, IconX } from '@tabler/icons'
import { notifications } from '@mantine/notifications'
import { useUISlice } from 'src/slices/ui'
import { useCreateWorkitem } from 'src/gen/work-item/work-item'
import { css } from '@emotion/react'

export default function CreateWorkItemForm() {
  const formSlice = useFormSlice()
  const uiSlice = useUISlice()

  const createWorkItemRequestSchema = JSON_SCHEMA.definitions.CreateWorkItemRequest
  // TODO: discriminated union generated by orval based on uiSlice.project.
  // orval could generate types based on discriminator:
  //  {projectName: "demo"; ...} | {projectName: "demo_two"; ...}

  const createWorkItemForm = useForm<CreateWorkItemRequest>({
    resolver: ajvResolver(createWorkItemRequestSchema as any, {
      strict: false,
      formats: fullFormats,
    }),
    mode: 'all',
    reValidateMode: 'onChange',
    defaultValues: {
      // ts discriminated type, must use switch for default values so we get type safety
      ...(uiSlice.project === 'demo' && {
        projectName: 'demo',
        demoProject: {},
      }),
      ...(uiSlice.project === 'demo_two' && {
        projectName: 'demo_two',
        demoTwoProject: {},
      }),
    },
  })
  const formName = 'createWorkItemForm'
  const createDemoWorkItem = useCreateWorkitem()
  const authorization = OPERATION_AUTH.CreateWorkitem

  const tour = useTour()

  return (
    <>
      <Button
        className="tour-button"
        onClick={(e) => {
          tour.setIsOpen(true)
        }}
      >
        Open tour
      </Button>
      <Space p={10} />
      <Button className="tour-button-example">Click to continue tour</Button>
      <h3>Authorization:</h3>
      <CodeHighlight code={JSON.stringify(authorization, null, '  ')} language="json" />
      <h3>Form:</h3>
      <FormProvider {...createWorkItemForm}>
        <DynamicForm<CreateWorkItemRequest, 'base.metadata' | 'projectName'>
          onSubmit={(e) => {
            e.preventDefault()
            createWorkItemForm.handleSubmit(
              (data) => {
                console.log({ data })
                createDemoWorkItem.mutate(
                  { data },
                  {
                    onSuccess(data, variables, context) {
                      formSlice.setCalloutErrors(formName, [])
                      console.log({ onSuccess: data })
                      notifications.show({
                        title: 'Success',
                        color: 'green',
                        icon: <IconCheck size="1.2rem" />,
                        autoClose: 5000,
                        message: 'Item created successfully',
                      })
                      createWorkItemForm.reset()
                    },
                    onError(error, variables, context) {
                      if (!error.response) return

                      // TODO: callouterror accepts httperror and will handle bare httperror and
                      // httperror with array of validationerror
                      console.log({ onError: error.response?.data })
                      formSlice.setCalloutErrors(formName, [error.response.data.detail])
                      notifications.show({
                        title: error.response.data.title,
                        color: 'red',
                        icon: <IconX size="1.2rem" />,
                        autoClose: 10000,
                        message: error.response.data.detail,
                      })
                    },
                  },
                )
              },
              (errors) => {
                console.log({ errors })
              },
            )(e)
          }}
          formName={formName}
          schemaFields={parseSchemaFields(
            uiSlice.project === 'demo'
              ? JSON_SCHEMA.definitions.CreateDemoWorkItemRequest
              : JSON_SCHEMA.definitions.CreateDemoTwoWorkItemRequest,
          )}
          options={{
            labels: {
              base: '',
              tagIDs: 'Tags',
              members: 'Members',
              demoProject: '',
              'base.title': 'Title',
              'base.description': 'Description',
              'base.kanbanStepID': 'Step',
              'base.targetDate': 'Target date',
              'base.teamID': 'Team',
              'base.workItemTypeID': 'Workitem type',
              'base.closedAt': 'Closed date',
              'members.role': 'Role',
              'members.userID': 'User',
              'demoProject.ref': 'Ref',
              'demoProject.line': 'Line',
              'demoProject.lastMessageAt': 'Last message date',
              'demoProject.reopened': 'Reopened',
              demoTwoProject: '',
              'demoTwoProject.customDateForProject2': 'Custom date',
            },
            propsOverride: {
              'base.description': {
                'data-tour-workitem-description-input': 'description-input',
              },
            },
            input: {
              'base.description': {
                component: <Textarea resize="vertical" styles={{ root: { width: '100%' } }} />,
              },
            },
          }}
        ></DynamicForm>
      </FormProvider>
    </>
  )
}
