FROM node:18.5.0-alpine

RUN npm i -g pnpm@6.32
WORKDIR /frontend

ENV PATH /frontend/node_modules/.bin:$PATH
ENV JQ_VERSION=1.6
ENV JSFOLDER=/frontend/config/*.json

RUN wget --no-check-certificate https://github.com/stedolan/jq/releases/download/jq-${JQ_VERSION}/jq-linux64 -O /tmp/jq-linux64
RUN cp /tmp/jq-linux64 /usr/bin/jq
RUN chmod +x /usr/bin/jq
RUN apk add --no-cache bash git openssh moreutils gettext

COPY ../frontend/pnpm-lock.yaml /frontend
COPY ../frontend/config.template.json /frontend
COPY ../frontend/replace-config.sh /frontend
RUN jq \
  'to_entries | map_values({ (.key) : ("$" + .key) }) | reduce .[] as $item ({}; . + $item)' \
  ./config.template.json > ./config.tmp.json && mv ./config.tmp.json ./config.template.json
RUN cat config.template.json
# TODO env is not loaded in dev:
# existing_vars are $YARN_VERSION,$PWD,$HOME,$JSFOLDER,$JQ_VERSION,$SHLVL,$PATH,$NODE_VERSION
RUN ./replace-config.sh
RUN cat config.json

ENV TSC_WATCHFILE "UseFsEventsWithFallbackDynamicPolling"
CMD ["pnpm", "run", "dev"]
