// Code generated by xo. DO NOT EDIT.

//lint:ignore

package got

type XoTestsTableEntity string

const (
	XoTestsTableEntityXoTestsBook                    XoTestsTableEntity = "xo_tests.books"
	XoTestsTableEntityXoTestsBookAuthor              XoTestsTableEntity = "xo_tests.book_authors"
	XoTestsTableEntityXoTestsBookAuthorsSurrogateKey XoTestsTableEntity = "xo_tests.book_authors_surrogate_key"
	XoTestsTableEntityXoTestsBookReview              XoTestsTableEntity = "xo_tests.book_reviews"
	XoTestsTableEntityXoTestsBookSeller              XoTestsTableEntity = "xo_tests.book_sellers"
	XoTestsTableEntityXoTestsCacheDemoWorkItem       XoTestsTableEntity = "xo_tests.cache__demo_work_items"
	XoTestsTableEntityXoTestsDemoWorkItem            XoTestsTableEntity = "xo_tests.demo_work_items"
	XoTestsTableEntityXoTestsDummyJoin               XoTestsTableEntity = "xo_tests.dummy_join"
	XoTestsTableEntityXoTestsNotification            XoTestsTableEntity = "xo_tests.notifications"
	XoTestsTableEntityXoTestsPagElement              XoTestsTableEntity = "xo_tests.pag_element"
	XoTestsTableEntityXoTestsTeam                    XoTestsTableEntity = "xo_tests.teams"
	XoTestsTableEntityXoTestsTimeEntry               XoTestsTableEntity = "xo_tests.time_entries"
	XoTestsTableEntityXoTestsUser                    XoTestsTableEntity = "xo_tests.users"
	XoTestsTableEntityXoTestsUserAPIKey              XoTestsTableEntity = "xo_tests.user_api_keys"
	XoTestsTableEntityXoTestsWorkItem                XoTestsTableEntity = "xo_tests.work_items"
	XoTestsTableEntityXoTestsWorkItemAssignee        XoTestsTableEntity = "xo_tests.work_item_assignee"
	XoTestsTableEntityXoTestsWorkItemComment         XoTestsTableEntity = "xo_tests.work_item_comments"
)

var XoTestsEntityFields = map[XoTestsTableEntity]map[string]DbField{
	XoTestsTableEntityXoTestsBook: {
		"bookID": DbField{Type: ColumnSimpleTypeInteger, Db: "book_id", Nullable: false, Public: true},
		"name":   DbField{Type: ColumnSimpleTypeString, Db: "name", Nullable: false, Public: true},
	},
	XoTestsTableEntityXoTestsBookAuthor: {
		"authorID":  DbField{Type: ColumnSimpleTypeString, Db: "author_id", Nullable: false, Public: true},
		"bookID":    DbField{Type: ColumnSimpleTypeInteger, Db: "book_id", Nullable: false, Public: true},
		"pseudonym": DbField{Type: ColumnSimpleTypeString, Db: "pseudonym", Nullable: true, Public: true},
	},
	XoTestsTableEntityXoTestsBookAuthorsSurrogateKey: {
		"authorID":                  DbField{Type: ColumnSimpleTypeString, Db: "author_id", Nullable: false, Public: true},
		"bookAuthorsSurrogateKeyID": DbField{Type: ColumnSimpleTypeInteger, Db: "book_authors_surrogate_key_id", Nullable: false, Public: true},
		"bookID":                    DbField{Type: ColumnSimpleTypeInteger, Db: "book_id", Nullable: false, Public: true},
		"pseudonym":                 DbField{Type: ColumnSimpleTypeString, Db: "pseudonym", Nullable: true, Public: true},
	},
	XoTestsTableEntityXoTestsBookReview: {
		"bookID":       DbField{Type: ColumnSimpleTypeInteger, Db: "book_id", Nullable: false, Public: true},
		"bookReviewID": DbField{Type: ColumnSimpleTypeInteger, Db: "book_review_id", Nullable: false, Public: true},
		"reviewer":     DbField{Type: ColumnSimpleTypeString, Db: "reviewer", Nullable: false, Public: true},
	},
	XoTestsTableEntityXoTestsBookSeller: {
		"bookID": DbField{Type: ColumnSimpleTypeInteger, Db: "book_id", Nullable: false, Public: true},
		"seller": DbField{Type: ColumnSimpleTypeString, Db: "seller", Nullable: false, Public: true},
	},
	XoTestsTableEntityXoTestsCacheDemoWorkItem: {
		"teamID":     DbField{Type: ColumnSimpleTypeInteger, Db: "team_id", Nullable: false, Public: true},
		"title":      DbField{Type: ColumnSimpleTypeString, Db: "title", Nullable: true, Public: true},
		"workItemID": DbField{Type: ColumnSimpleTypeInteger, Db: "work_item_id", Nullable: false, Public: true},
	},
	XoTestsTableEntityXoTestsDemoWorkItem: {
		"checked":    DbField{Type: ColumnSimpleTypeBoolean, Db: "checked", Nullable: false, Public: true},
		"workItemID": DbField{Type: ColumnSimpleTypeInteger, Db: "work_item_id", Nullable: false, Public: true},
	},
	XoTestsTableEntityXoTestsDummyJoin: {
		"dummyJoinID": DbField{Type: ColumnSimpleTypeInteger, Db: "dummy_join_id", Nullable: false, Public: true},
		"name":        DbField{Type: ColumnSimpleTypeString, Db: "name", Nullable: true, Public: true},
	},
	XoTestsTableEntityXoTestsNotification: {
		"body":           DbField{Type: ColumnSimpleTypeString, Db: "body", Nullable: false, Public: true},
		"notificationID": DbField{Type: ColumnSimpleTypeInteger, Db: "notification_id", Nullable: false, Public: true},
		"receiver":       DbField{Type: ColumnSimpleTypeString, Db: "receiver", Nullable: true, Public: true},
		"sender":         DbField{Type: ColumnSimpleTypeString, Db: "sender", Nullable: false, Public: true},
	},
	XoTestsTableEntityXoTestsPagElement: {
		"createdAt":          DbField{Type: ColumnSimpleTypeDateTime, Db: "created_at", Nullable: false, Public: true},
		"dummy":              DbField{Type: ColumnSimpleTypeInteger, Db: "dummy", Nullable: true, Public: true},
		"name":               DbField{Type: ColumnSimpleTypeString, Db: "name", Nullable: false, Public: true},
		"paginatedElementID": DbField{Type: ColumnSimpleTypeString, Db: "paginated_element_id", Nullable: false, Public: true},
	},
	XoTestsTableEntityXoTestsTeam: {
		"name":   DbField{Type: ColumnSimpleTypeString, Db: "name", Nullable: false, Public: true},
		"teamID": DbField{Type: ColumnSimpleTypeInteger, Db: "team_id", Nullable: false, Public: true},
	},
	XoTestsTableEntityXoTestsTimeEntry: {
		"start":       DbField{Type: ColumnSimpleTypeDateTime, Db: "start", Nullable: false, Public: true},
		"timeEntryID": DbField{Type: ColumnSimpleTypeInteger, Db: "time_entry_id", Nullable: false, Public: true},
		"workItemID":  DbField{Type: ColumnSimpleTypeInteger, Db: "work_item_id", Nullable: true, Public: true},
	},
	XoTestsTableEntityXoTestsUser: {
		"apiKeyID":  DbField{Type: ColumnSimpleTypeInteger, Db: "api_key_id", Nullable: true, Public: true},
		"createdAt": DbField{Type: ColumnSimpleTypeDateTime, Db: "created_at", Nullable: false, Public: true},
		"deletedAt": DbField{Type: ColumnSimpleTypeDateTime, Db: "deleted_at", Nullable: true, Public: true},
		"name":      DbField{Type: ColumnSimpleTypeString, Db: "name", Nullable: false, Public: true},
		"userID":    DbField{Type: ColumnSimpleTypeString, Db: "user_id", Nullable: false, Public: true},
	},
	XoTestsTableEntityXoTestsUserAPIKey: {
		"apiKey":       DbField{Type: ColumnSimpleTypeString, Db: "api_key", Nullable: false, Public: true},
		"expiresOn":    DbField{Type: ColumnSimpleTypeDateTime, Db: "expires_on", Nullable: false, Public: true},
		"userAPIKeyID": DbField{Type: ColumnSimpleTypeInteger, Db: "user_api_key_id", Nullable: false, Public: true},
		"userID":       DbField{Type: ColumnSimpleTypeString, Db: "user_id", Nullable: false, Public: true},
	},
	XoTestsTableEntityXoTestsWorkItem: {
		"description": DbField{Type: ColumnSimpleTypeString, Db: "description", Nullable: true, Public: true},
		"teamID":      DbField{Type: ColumnSimpleTypeInteger, Db: "team_id", Nullable: false, Public: true},
		"title":       DbField{Type: ColumnSimpleTypeString, Db: "title", Nullable: true, Public: true},
		"workItemID":  DbField{Type: ColumnSimpleTypeInteger, Db: "work_item_id", Nullable: false, Public: true},
	},
	XoTestsTableEntityXoTestsWorkItemAssignee: {
		"assignee":   DbField{Type: ColumnSimpleTypeString, Db: "assignee", Nullable: false, Public: true},
		"workItemID": DbField{Type: ColumnSimpleTypeInteger, Db: "work_item_id", Nullable: false, Public: true},
	},
	XoTestsTableEntityXoTestsWorkItemComment: {
		"createdAt":         DbField{Type: ColumnSimpleTypeDateTime, Db: "created_at", Nullable: false, Public: true},
		"message":           DbField{Type: ColumnSimpleTypeString, Db: "message", Nullable: false, Public: true},
		"updatedAt":         DbField{Type: ColumnSimpleTypeDateTime, Db: "updated_at", Nullable: false, Public: true},
		"userID":            DbField{Type: ColumnSimpleTypeString, Db: "user_id", Nullable: false, Public: true},
		"workItemCommentID": DbField{Type: ColumnSimpleTypeInteger, Db: "work_item_comment_id", Nullable: false, Public: true},
		"workItemID":        DbField{Type: ColumnSimpleTypeInteger, Db: "work_item_id", Nullable: false, Public: true},
	},
}
