name: OpenAPI check

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "main"
          submodules: recursive
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/setup
      - name: Diff OpenAPI spec
        run: |
          source .envrc

          [[ $(git branch --show-current) != "main" ]] && git fetch origin main:main
          project diff-oas --x-env=ci
